apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: LoadBalancer
  ports:
  - name: elk-kibana
    port: 5601
    targetPort: "5601-port"
  - name: storm-nimbus
    port: 8080
    targetPort: "8080-port"
  - name: nginx
    port: 80
    targetPort: "80-port"
  selector:
    lbtype: external
